spring.application.name=autospec-api

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/autospec
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=AutoSpecFordFiap2026ChaveSecretaJWTSegura123456789
jwt.expiration=3600000